### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by tarasratushny** [crashinvaders/gdx-texture-packer-gui#103] opened 2021-05-08 22:23 UTC
Opened window to select atlas output directory, then in path line deleted one directory and app crashed.

Version: 4.10.0
OS: Windows 10 10.0 amd64
JRE: 15.0.2 Oracle Corporation
GPU: GeForce GTX 1080 Ti/PCIe/SSE2
OpenGL vendor: NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 460.89
[ExtensionModuleRepositoryService] Cached data was loaded
[ExtensionModuleRepositoryService] Cached data is outdated.
[ExtensionModuleRepositoryService] Requesting new data from remote server.
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected problems and runtime exceptions.
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
[ExtensionModuleRepositoryService] Data was loaded from remote server.
java.lang.IllegalArgumentException: actor cannot be null.
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getCell(Table.java:417)
	at com.kotcrab.vis.ui.widget.MenuItem.getImageCell(MenuItem.java:352)
	at com.kotcrab.vis.ui.widget.file.internal.AbstractSuggestionPopup.createMenuItem(AbstractSuggestionPopup.java:36)
	at com.kotcrab.vis.ui.widget.file.internal.DirsSuggestionPopup$1$1.run(DirsSuggestionPopup.java:88)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:157)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)

**Comment by metaphore** [comment] 2021-05-09 05:50
Thanks for the report.
Looks like a duplicate of https://github.com/crashinvaders/gdx-texture-packer-gui/issues/98 and it should be fixed in the next release.

**Closed by metaphore** 2021-05-09 05:50 UTC
Labels: crash report
