### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by norappmob** [crashinvaders/gdx-texture-packer-gui#104] opened 2021-05-09 15:49 UTC
<details><summary>Application Log</summary>

```
Version: 4.10.0
OS: Linux 5.3.18-lp152.72-preempt amd64
JRE: 11.0.10 Oracle Corporation
GPU: Radeon RX 580 Series (POLARIS10, DRM 3.33.0, 5.3.18-lp152.72-preempt, LLVM 9.0.1)
OpenGL vendor: X.Org
OpenGL version: 4.5 (Compatibility Profile) Mesa 19.3.4
[ExtensionModuleRepositoryService] Cached data was loaded
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected problems and runtime exceptions.
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
Packing is started
Packing.........
Writing 512x512: /mnt/Datos/Programacion/Android/Apps/Proximo Juego/baseLanzamiento.png
Packing is done
Total pack files size is 204863 bytes
1 pages
Total processing time: 0.26sec

Packing is started
Packing.........
Writing 512x512: /mnt/Datos/Programacion/Android/Apps/Proximo Juego/baseLanzamiento.png
Packing is done
Total pack files size is 204788 bytes
1 pages
Total processing time: 0.08sec

java.lang.RuntimeException: Actor: base
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.Stage.keyDown(Stage.java:418)
	at com.crashinvaders.common.PrioritizedInputMultiplexer$Wrapper.keyDown(PrioritizedInputMultiplexer.java:120)
	at com.crashinvaders.common.PrioritizedInputMultiplexer.keyDown(PrioritizedInputMultiplexer.java:51)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:75)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:187)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: java.lang.StringIndexOutOfBoundsException: String index out of range: -1
	at java.base/java.lang.String.substring(String.java:1841)
	at com.crashinvaders.texturepackergui.utils.PathUtils.relativize(PathUtils.java:96)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.serializePack(ProjectSerializer.java:128)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.serializeProject(ProjectSerializer.java:97)
	at com.crashinvaders.texturepackergui.controllers.projectserializer.ProjectSerializer.saveProject(ProjectSerializer.java:55)
	at com.crashinvaders.texturepackergui.controllers.GlobalActions$5.selected(GlobalActions.java:251)
	at com.kotcrab.vis.ui.widget.file.FileChooser.notifyListenerAndCloseDialog(FileChooser.java:727)
	at com.kotcrab.vis.ui.widget.file.FileChooser.selectionFinished(FileChooser.java:689)
	at com.kotcrab.vis.ui.widget.file.FileChooser.access$2200(FileChooser.java:76)
	at com.kotcrab.vis.ui.widget.file.FileChooser$15.keyDown(FileChooser.java:548)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:53)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 11 more
```
</details>

**Comment by metaphore** [comment] 2021-05-09 22:20
Thanks for the report.
It's there anything specific I could try to reproduce this crash?

**Comment by metaphore** [comment] 2021-09-15 01:59
As there are no extra details provided I presume this one is a duplicate of https://github.com/crashinvaders/gdx-texture-packer-gui/issues/98

**Closed by metaphore** 2021-09-15 01:59 UTC
Labels: crash report
