### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by argallo** [crashinvaders/gdx-texture-packer-gui#124] opened 2021-12-14 06:05 UTC
> Please paste the crash log in here (already in your clipboard) and, if possible, provide any information that may help to reproduce the issue.
<details><summary>Application Log</summary>

```
Version: 4.10.1
OS: Windows 10 10.0 amd64
JRE: 1.8.0_242-release JetBrains s.r.o
GPU: NVIDIA GeForce RTX 3080/PCIe/SSE2
OpenGL vendor: NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 496.76
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
com.badlogic.gdx.utils.GdxRuntimeException: Unable to invoke method: initiateFirstScreen of type: com.github.czyzby.autumn.mvc.component.ui.InterfaceService@67d48005 with parameters: []
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:50)
	at com.github.czyzby.autumn.processor.impl.InitiateAnnotationProcessor.doAfterScanning(InitiateAnnotationProcessor.java:42)
	at com.github.czyzby.autumn.context.ContextInitializer.invokeProcessorActionsAfterInitiation(ContextInitializer.java:351)
	at com.github.czyzby.autumn.context.ContextInitializer.initiate(ContextInitializer.java:294)
	at com.crashinvaders.texturepackergui.App.initiateContext(App.java:100)
	at com.crashinvaders.texturepackergui.App.create(App.java:85)
	at com.crashinvaders.texturepackergui.desktop.ApplicationListenerWrapper.create(ApplicationListenerWrapper.java:14)
	at com.crashinvaders.texturepackergui.desktop.Lwjgl3AppWrapper.create(Lwjgl3AppWrapper.java:43)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.initializeListener(Lwjgl3Window.java:433)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:381)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:143)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:116)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:57)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: com.badlogic.gdx.utils.reflect.ReflectionException: Exception occurred in method: initiateFirstScreen
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:114)
	at com.github.czyzby.kiwi.util.gdx.reflection.Reflection.invokeMethod(Reflection.java:130)
	at com.github.czyzby.autumn.context.impl.method.MethodInvocation.invoke(MethodInvocation.java:47)
	... 13 more
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.badlogic.gdx.utils.reflect.Method.invoke(Method.java:108)
	... 15 more
Caused by: com.badlogic.gdx.utils.GdxRuntimeException: At least one view has to be set as first.
	at com.github.czyzby.autumn.mvc.component.ui.InterfaceService.initiateFirstScreen(InterfaceService.java:199)
	... 20 more
```
</details>

**Comment by metaphore** [comment] 2021-12-14 22:31
@argallo thanks for the report!
It looks like a duplicate of #92. Let's move to the older issue and continue in there.

**Closed by metaphore** 2021-12-14 22:31 UTC
Labels: crash report
