### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by dangnguyendota** [crashinvaders/gdx-texture-packer-gui#107] opened 2021-06-05 03:34 UTC
<details><summary>Application Log</summary>

```
Version: 4.10.0
OS: Linux 5.8.0-55-generic amd64
JRE: 11.0.11 Ubuntu
GPU: Mesa Intel(R) HD Graphics 5500 (BDW GT2)
OpenGL vendor: Intel
OpenGL version: 4.6 (Compatibility Profile) Mesa 20.0.8
[ExtensionModuleRepositoryService] Cached data was loaded
[ExtensionModuleRepositoryService] Cached data is outdated.
[ExtensionModuleRepositoryService] Requesting new data from remote server.
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected problems and runtime exceptions.
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
[ExtensionModuleRepositoryService] Data was loaded from remote server.
Packing is started
Packing.........
Writing 2048x2048: /home/dangnguyendota/Desktop/backup/code/skmer/skmer-client/android/assets/ui/lobby.png
Packing is done
Total pack files size is 2024587 bytes
1 pages
Total processing time: 3.49sec

java.lang.RuntimeException: Actor: l
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.badlogic.gdx.scenes.scene2d.Stage.keyTyped(Stage.java:446)
	at com.crashinvaders.common.PrioritizedInputMultiplexer$Wrapper.keyTyped(PrioritizedInputMultiplexer.java:128)
	at com.crashinvaders.common.PrioritizedInputMultiplexer.keyTyped(PrioritizedInputMultiplexer.java:65)
	at com.badlogic.gdx.InputEventQueue.drain(InputEventQueue.java:81)
	at com.badlogic.gdx.backends.lwjgl3.DefaultLwjgl3Input.update(DefaultLwjgl3Input.java:187)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Window.update(Lwjgl3Window.java:394)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:141)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
Caused by: java.lang.RuntimeException: Actor: l
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:192)
	at com.badlogic.gdx.scenes.scene2d.Actor.fire(Actor.java:152)
	at com.kotcrab.vis.ui.widget.VisTextField.changeText(VisTextField.java:702)
	at com.kotcrab.vis.ui.widget.VisTextField$TextFieldClickListener.keyTyped(VisTextField.java:1232)
	at com.badlogic.gdx.scenes.scene2d.InputListener.handle(InputListener.java:57)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 11 more
Caused by: java.lang.IllegalArgumentException: actor cannot be null.
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getCell(Table.java:417)
	at com.kotcrab.vis.ui.widget.MenuItem.getImageCell(MenuItem.java:352)
	at com.kotcrab.vis.ui.widget.file.internal.AbstractSuggestionPopup.createMenuItem(AbstractSuggestionPopup.java:36)
	at com.kotcrab.vis.ui.widget.file.internal.FileSuggestionPopup.createSuggestions(FileSuggestionPopup.java:55)
	at com.kotcrab.vis.ui.widget.file.internal.FileSuggestionPopup.pathFieldKeyTyped(FileSuggestionPopup.java:41)
	at com.kotcrab.vis.ui.widget.file.FileChooser$16.changed(FileChooser.java:558)
	at com.badlogic.gdx.scenes.scene2d.utils.ChangeListener.handle(ChangeListener.java:28)
	at com.badlogic.gdx.scenes.scene2d.Actor.notify(Actor.java:188)
	... 16 more
```
</details>

**Comment by metaphore** [comment] 2021-10-03 09:05
Looks like a duplicate of #112 
Please feel free to provide details and reopen if that's something else.

**Closed by metaphore** 2021-10-03 09:05 UTC
Labels: crash report
