### ISSUE TITLE
File path editing for FileChooser may result in a crash.

### ISSUE THREAD

**Issue by xavmag** [crashinvaders/gdx-texture-packer-gui#98] opened 2021-02-02 01:59 UTC
<details><summary>Application Log</summary>

```
Version: 4.10.0
OS: Windows 10 10.0 x86
JRE: 1.8.0_231 Oracle Corporation
GPU: GeForce MX150/PCIe/SSE2
OpenGL vendor: NVIDIA Corporation
OpenGL version: 4.6.0 NVIDIA 460.79
[ExtensionModuleRepositoryService] Cached data is outdated.
[ExtensionModuleRepositoryService] Requesting new data from remote server.
[ConfigurationController] Incremental fonts are disabled
[VisUI] Warning, using invalid libGDX version for VisUI 1.4.8.
You are using libGDX 1.9.11 but you need 1.9.12. This may cause unexpected problems and runtime exceptions.
[GlobalShortcutHandler] Parsing shortcut file: hotkeys_default.txt
[ExtensionModuleRepositoryService] Data was loaded from remote server.
[text-red]Exception occurred:[] There is no input files to perform packing
[text-red]Stack trace:[] 
java.lang.IllegalStateException: There is no input files to perform packing
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:25)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

[text-red]Exception occurred:[] There is no input files to perform packing
[text-red]Stack trace:[] 
java.lang.IllegalStateException: There is no input files to perform packing
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:25)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Packing is started
Packing............
Writing 2048x128: C:\projects\LibGDX\prototype\android\assets\grey.png
Packing is done
Total pack files size is 20468 bytes
1 pages
Total processing time: 0.38sec

Packing is started
Packing.........
Writing 512x256: C:\projects\LibGDX\prototype\android\assets\yellow.png
Packing is done
Total pack files size is 17187 bytes
1 pages
Total processing time: 0.10sec

Packing is started
Packing.........
Writing 512x256: C:\projects\LibGDX\prototype\android\assets\red.png
Packing is done
Total pack files size is 18149 bytes
1 pages
Total processing time: 0.10sec

Packing is started
Packing............
Writing 2048x128: C:\projects\LibGDX\prototype\android\assets\grey.png
Packing is done
Total pack files size is 20582 bytes
1 pages
Total processing time: 0.15sec

[text-red]Exception occurred:[] Output directory is not specified
[text-red]Stack trace:[] 
java.lang.IllegalStateException: Output directory is not specified
	at com.crashinvaders.texturepackergui.controllers.packing.processors.DataValidationProcessor.processPackage(DataValidationProcessor.java:22)
	at com.crashinvaders.texturepackergui.utils.packprocessing.CompositePackProcessor.processPackage(CompositePackProcessor.java:20)
	at com.crashinvaders.texturepackergui.utils.packprocessing.PackProcessingManager.lambda$execute$0(PackProcessingManager.java:60)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

java.lang.IllegalArgumentException: actor cannot be null.
	at com.badlogic.gdx.scenes.scene2d.ui.Table.getCell(Table.java:417)
	at com.kotcrab.vis.ui.widget.MenuItem.getImageCell(MenuItem.java:352)
	at com.kotcrab.vis.ui.widget.file.internal.AbstractSuggestionPopup.createMenuItem(AbstractSuggestionPopup.java:36)
	at com.kotcrab.vis.ui.widget.file.internal.DirsSuggestionPopup$1$1.run(DirsSuggestionPopup.java:88)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.loop(Lwjgl3Application.java:157)
	at com.badlogic.gdx.backends.lwjgl3.Lwjgl3Application.<init>(Lwjgl3Application.java:117)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.start(ApplicationStarter.java:56)
	at com.crashinvaders.texturepackergui.desktop.ApplicationStarter.main(ApplicationStarter.java:35)
```
</details>

How to produce the bug
1. Create new atlas
2. Open the browse window to choose the output directory
3. Highlight all the text after the last backward slash in the path bar
4. Press `backspace`

**Comment by metaphore** [comment] 2021-02-02 12:18
Nicely spotted, thanks a lot! I can reproduce it on my end.
Probably a bug in the VisUI `FileChooser` widget.
Let's see if @kotcrab is aware of this one (it's VisUI 1.4.8)?

**Comment by kotcrab** [comment] 2021-02-02 12:33
Thanks, looks like this is caused by this change https://github.com/libgdx/libgdx/commit/f829dfc2db47f85b3da9ec3ca08fab5ec3b7c8be doesn't seem to be in the change log. Anyway, I'll fix it.

**Comment by metaphore** [comment] 2021-02-02 12:34
Thanks @kotcrab!

**Comment by kotcrab** [comment] 2021-02-02 12:49
Fixed in https://github.com/kotcrab/vis-ui/commit/aa0184c742d7b5607921901ceabf41460c460a34. The libgdx change is okay, it really worked by accident before.

**Comment by metaphore** [comment] 2021-05-16 15:07
All good, should be fixed in the next release.

**Closed by metaphore** 2021-05-16 15:07 UTC
Labels: bug, crash report
